name: Feature Reuest
description: Ask for a new feature for the Home Assistant UniFi Protect Integration
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
  - type: textarea
    id: related-to-bug
    attributes:
      label: Feature related to bug
      description: Is your feature request related to a problem?
      placeholder: Please describe
    validations:
      required: false
  - type: textarea
    id: new-feature
    attributes:
      label: New Feature
      description: Please describe in detail what feature you would like to have.
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
