default_config:

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 2

debugpy:
  start: false

http:
  server_port: 9123

logger:
  default: warning
  logs:
    pyunifiprotect: debug
    custom_components.unifiprotect: debug
