blueprint:
  name: Send Doorbell Notification (simple)
  description: Send a simple notification when someone rings the doorbell.
  domain: automation
  input:
    doorbell:
      name: Doorbell Sensor
      description: The doorbell binary sensor for your Doorbell
      selector:
        entity:
          integration: unifiprotect
          domain: binary_sensor
          device_class: occupancy
    title:
      name: Notification Title
      description: Title for Notification
      default: Doorbell!
      selector:
        text:
    channel:
      name: Notification Channel
      description: Notification channel/group to use. https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-channels
      default: Doorbell
      selector:
        text:

variables:
  doorbell: !input doorbell
  title: !input title
  channel: !input channel
  tag: "{{ channel.lower().replace(' ', '-') }}"
  message: "Someone rang the doorbell at {{
    as_local(states[doorbell].last_changed).strftime('%I:%M
    %p') }}!"

trigger:
  - platform: state
    entity_id: !input doorbell
    from: "off"
    to: "on"

action:
  - service: notify.notify
    data:
      message: "{{ message }}"
      title: "{{ title }}"
      data:
        # Android/iOS notification grouping
        group: "{{ tag }}"
        # Android notification Channel
        channel: "{{ channel }}"
        # Android high prority
        ttl: 0
        priority: high
        # iOS high prority
        time-sensitive: 1
  - service: notify.push_notification
    data:
      message: "{{ message }}"
      title: Front Door
      data:
        # HTML5 Notification tag
        tag: "{{ tag }}"
