blueprint:
  name: Send Doorbell Notification (image)
  description: Send a notification when someone rings the doorbell with a image.
  domain: automation
  input:
    doorbell:
      name: Doorbell Sensor
      description: The doorbell binary sensor for your Doorbell
      selector:
        entity:
          integration: unifiprotect
          domain: binary_sensor
          device_class: occupancy
    camera:
      name: Camera Entity
      description: The camera to pull the image from on notification
      selector:
        entity:
          integration: unifiprotect
          domain: camera
    title:
      name: Notification Title
      description: Title for Notification
      default: Doorbell!
      selector:
        text:
    channel:
      name: Notification Channel
      description: Notification channel/group to use. https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-channels
      default: Doorbell
      selector:
        text:
    base_ha_url:
      name: Base Home Assistant URL
      description: Base URL to use for opening HA links in HTML5 notifications.
      default: http://homeassistant.local:8123
      selector:
        text:
    base_image_url:
      name: Base Image URL
      description: Publically accesible base URL for your Home Assistant instance. May diff from your Base Home Assistant URL if your HA instance not publically accessible. **Must be an HTTPS URL with a valid certificate**.
      default: https://example.com
      selector:
        text:
    lovelace_view:
      name: Lovelace
      description: Home Assistant Lovelace view to open when clicking notification
      default: /lovelace/home

variables:
  doorbell: !input doorbell
  camera: !input camera
  title: !input title
  channel: !input channel
  tag: "{{ channel.lower().replace(' ', '-') }}"
  message: "Someone rang the doorbell at {{ as_local(states[doorbell].last_changed).strftime('%I:%M %p') }}!"
  image: "{{ base_image_url }}{{ state_attr(camera, 'entity_picture') }}"
  view: !input lovelace_view
  base_url: !input base_ha_url

trigger:
  - platform: state
    entity_id: !input doorbell
    from: "off"
    to: "on"

action:
  - service: notify.notify
    data:
      message: "{{ message }}"
      title: "{{ title }}"
      data:
        # Android/iOS notification grouping
        group: "{{ tag }}"
        # Android notification Channel
        channel: "{{ channel }}"
        # Android high prority
        ttl: 0
        priority: high
        # iOS high prority
        time-sensitive: 1
        image: "{{ image }}"
        actions:
          - action: URI
            title: Open App
            uri: "{{ view }}"
  - service: notify.push_notification
    data:
      message: "{{ message }}"
      title: "{{ title }}"
      data:
        # HTML5 Notification tag
        tag: "{{ tag }}"
        image: "{{ image }}"
        url: "{{ base_url }}{{ view }}"
