blueprint:
  name: Send Smart Detection Notification (simple)
  description: Send a simple notification when a smart detection is detected by camera.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion binary sensor for your Camera
      selector:
        entity:
          integration: unifiprotect
          domain: binary_sensor
          device_class: motion
    title:
      name: Notification Title
      description: Title for Notification
      default: Motion!
      selector:
        text:
    channel:
      name: Notification Channel
      description: Notification channel/group to use. https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-channels
      default: Motion
      selector:
        text:
    cooldown:
      name: Notification Cooldown
      description: Not much time must pass before the notification can be fired again. In minutes.
      default: 2
      selector:
        number:
          min: 0
          max: 720
          step: 1
          mode: box

variables:
  motion_sensor: !input motion_sensor
  title: !input title
  channel: !input channel
  tag: "{{ channel.lower().replace(' ', '-') }}"
  message: "{{ state_attr(motion_sensor, 'event_object').title() }} detected by {{ states[motion_sensor].name }} at {{ as_local(states[motion_sensor].last_changed).strftime('%I:%M %p') }}!"

trigger:
  - platform: state
    entity_id: !input motion_sensor
    attribute: event_object
    to:
      - person
      - vehicle

action:
  - service: notify.notify
    data:
      message: "{{ message }}"
      title: "{{ title }}"
      data:
        # Android/iOS notification grouping
        group: "{{ tag }}"
        # Android notification Channel
        channel: "{{ channel }}"
        # Android high prority
        ttl: 0
        priority: high
        # iOS high prority
        time-sensitive: 1
  - service: notify.push_notification
    data:
      message: "{{ message }}"
      title: "{{ title }}"
      data:
        # HTML5 Notification tag
        tag: "{{ tag }}"
  - delay:
      minutes: !input cooldown
