blueprint:
  name: Doorbell Notification Callback
  description: Callback for the doorbell notification for the "Unlock Door" actionable notification.
  domain: automation
  input:
    unlock_action:
      name: Unlock Callback Action
      description: Callback action name. **Must** match the "Unlock Callback Action" for your doorbell notification automation.
      default: unlock_door
      selector:
        text:
    lock:
      name: Lock
      description: The lock to unlock when callback is fired.
      selector:
        entity:
          domain: lock

trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: !input unlock_action
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: !input unlock_action

action:
  - service: lock.unlock
    entity_id: !input lock
